### ISSUE TITLE
Invalid Tags for Golang Project.

### ISSUE THREAD

**Issue by iqDF** [zenthangplus/goccm#3]
Hi. I saw that the tags you are using is 2 digits (x.x) while golang requires 3 digits in the format of vmajor.minor.patch.

Will you be able to add tags for v1.1.0? Then my golang can download your project with the correct tags. Otherwise golang will default to pseudo tags which is non-human readable. 

Currently if I downloaded you tag from latest branch, it will looks like 
```
module github.com/iqdf/myrepo

go 1.14

require (
  github.com/zenthangplus/goccm v0.0.0-20211005163543-2f2e522aca15
)
```

**Comment by zenthangplus** [comment]
New versions correct to semver now
